language: node_js
sudo: required
before_install:
  sudo apt-get update
  sudo apt-get install xvfb
  sudo apt-get install libfontconfig
  wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  tar -xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  cd wkhtmltox/bin/
  sudo mv wkhtmltopdf /usr/bin/wkhtmltopdf
  sudo chmod a+x /usr/bin/wkhtmltopdf
script:
  - npm run build
