language: node_js
sudo: required
before_install:
  sudo apt-get update
  sudo apt-get install xvfb
  sudo apt-get install libfontconfig
  wget https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  sudo mv wkhtmltox/bin/wkhtmltopdf /usr/local/bin
script:
  - npm run build
