language: node_js
sudo: required
before_install:
  sudo apt-get update
  sudo apt-get install xvfb libfontconfig wkhtmltopdf
script:
  - npm run build
after_success:
  - '[[ $TRAVIS_BRANCH = "master" && $TRAVIS_PULL_REQUEST_BRANCH = "" ]] &&
    (npm install -g travis-deploy-once && travis-deploy-once "npm run semantic-release")'
