language: node_js
sudo: required
before_install:
  sudo apt-get update
  sudo apt-get install xvfb
  sudo apt-get install libfontconfig
  wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.trusty_amd64.deb
  sudo dpkg -i  wkhtmltox_0.12.5-1.trusty_amd64.deb 
  sudo apt -f install
script:
  - npm run build
