language: node_js
sudo: required
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-5 g++-5
  - sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - sudo apt-get install xvfb
  - sudo apt-get install libfontconfig
  - sudo apt-get install wkhtmltopdf
script:
  - npm run build
after_success:
  - '[[ $TRAVIS_BRANCH = "master" && $TRAVIS_PULL_REQUEST_BRANCH = "" ]] &&
    (npm install -g travis-deploy-once && travis-deploy-once "npm run semantic-release")'
